services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: public

  KeycloakAuthBundle\:
    resource: "../../"
    exclude:
      - "../../{DependencyInjection, Resources}"
      - "../../Domain/Model"
      - "../../Infrastructure/Symfony/Models"
      - "../../Infrastructure/Symfony/Event"

  # Port → Adapter (hexagonal)
  KeycloakAuthBundle\Domain\Port\JwksProviderInterface:
    alias: KeycloakAuthBundle\Infrastructure\Keycloak\JwksProvider

  KeycloakAuthBundle\Domain\Port\TokenExchangerInterface:
    alias: KeycloakAuthBundle\Infrastructure\Keycloak\TokenExchanger

  KeycloakAuthBundle\Infrastructure\Keycloak\JwksProvider:
    arguments:
      $httpClient: "@http_client"
      $jwksUrl: "%keycloak.jwks_url%"

  # UseCase service
  KeycloakAuthBundle\Application\UseCase\AuthenticateUser: ~

  "@keycloak_authenticator":
    alias: KeycloakAuthBundle\Infrastructure\Symfony\Security\KeycloakAuthenticator
  "@Symfony_user_provider":
    alias: KeycloakAuthBundle\Infrastructure\Symfony\Provider\SymfonyUserProvider

  # Authenticator service
  KeycloakAuthBundle\Infrastructure\Symfony\Security\KeycloakAuthenticator:
    arguments:
      $authenticateUser: '@KeycloakAuthBundle\Application\UseCase\AuthenticateUser'
    tags:
      - { name: "security.authenticator" }

  KeycloakAuthBundle\Infrastructure\Keycloak\LoginUrlGenerator:
    arguments:
      $baseUrl: "%keycloak.base_url%"
      $realm: "%keycloak.realm%"
      $clientId: "%keycloak.client_id%"
      $redirectUri: "%keycloak.redirect_uri%"

  KeycloakAuthBundle\Infrastructure\Keycloak\KeycloakEndpoints:
    arguments:
      $baseUrl: "%keycloak.base_url%"
      $realm: "%keycloak.realm%"

  KeycloakAuthBundle\Infrastructure\Keycloak\TokenExchanger:
    arguments:
      $clientId: "%keycloak.client_id%"
      $redirectUri: "%keycloak.redirect_uri%"
      $clientSecret: "%keycloak.client_secret%"

  KeycloakAuthBundle\Infrastructure\Keycloak\ClientCredentialsTokenProvider:
    arguments:
      $clientId: "%keycloak.client_id%"
      $clientSecret: "%keycloak.client_secret%"

  KeycloakAuthBundle\Infrastructure\Keycloak\IssuerChecker:
    arguments:
      $baseUrl: "%keycloak.base_url%"
      $realm: "%keycloak.realm%"

  KeycloakAuthBundle\Domain\Port\HealthCheckInterface:
    alias: KeycloakAuthBundle\Infrastructure\Keycloak\KeyCloackHealthChecker

  KeycloakAuthBundle\Infrastructure\Keycloak\Jwt\LcobucciJwtValidator:
    arguments:
      $jwtConfig: '@Lcobucci\JWT\Configuration' # ou ton service Configuration
      $jwksProvider: '@KeycloakAuthBundle\Infrastructure\Keycloak\JwksProvider'
      $roleMapper: '@KeycloakAuthBundle\Infrastructure\Keycloak\RoleMapper'
      $issuer: "%keycloak.issuer%"

  KeycloakAuthBundle\Domain\Port\RoleMapperInterface:
    alias: KeycloakAuthBundle\Infrastructure\Keycloak\RoleMapper

  # JWT and security authenticator
  Lcobucci\JWT\Signer\Key\InMemory:
    factory: ['Lcobucci\JWT\Signer\Key\InMemory', "empty"]

  Lcobucci\JWT\Signer\Rsa\Sha256:
    class: Lcobucci\JWT\Signer\Rsa\Sha256

  Lcobucci\JWT\Configuration:
    factory: ['Lcobucci\JWT\Configuration', "forAsymmetricSigner"]
    arguments:
      - '@Lcobucci\JWT\Signer\Rsa\Sha256'
      - '@Lcobucci\JWT\Signer\Key\InMemory'
      - '@Lcobucci\JWT\Signer\Key\InMemory'

  # Resolver
  KeycloakAuthBundle\Infrastructure\Symfony\RateLimiter\RateLimitHttpResolverAdapter:
    arguments:
      $requestStack: "@request_stack"
      $allowedPaths: "%keycloak.rate_limiter.allowed_paths%"
      $clientId: "%keycloak.client_id%"
      $strategies: "%keycloak.rate_limiter.strategies%"

  KeycloakAuthBundle\Domain\Port\RateLimitKeyResolverInterface:
    alias: KeycloakAuthBundle\Infrastructure\Symfony\RateLimiter\RateLimitHttpResolverAdapter

  KeycloakAuthBundle\Domain\Port\RateLimiterCheckerInterface:
    alias: KeycloakAuthBundle\Infrastructure\Symfony\RateLimiter\RateLimitAdapter

  KeycloakAuthBundle\Infrastructure\Symfony\RateLimiter\RateLimitAdapter:
    arguments:
      $factory:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        factory: ['Symfony\Component\RateLimiter\RateLimiterFactory', "create"]

  # prometheus metrics
  KeycloakAuthBundle\Infrastructure\Monitoring\Storage\RedisStorage:
    arguments:
      $host: "%keycloak.prometheus.redis.host%"
      $port: "%keycloak.prometheus.redis.port%"
      $prefix: "%keycloak.prometheus.redis.prefix%"
      $timeout: "%keycloak.prometheus.redis.timeout%"
      $readTimeout: "%keycloak.prometheus.redis.read_timeout%"
      $persistentConnections: "%keycloak.prometheus.redis.persistent_connections%"

  KeycloakAuthBundle\Infrastructure\Monitoring\Storage\APCStorage: ~

  KeycloakAuthBundle\Infrastructure\Monitoring\CollectorRegistryFactory: ~
  keycloak.prometheus.registry:
    class: Prometheus\CollectorRegistry
    factory:
      [
        '@KeycloakAuthBundle\Infrastructure\Monitoring\CollectorRegistryFactory',
        "create",
      ]

  Prometheus\CollectorRegistry:
    alias: keycloak.prometheus.registry

  KeycloakAuthBundle\Infrastructure\Monitoring\Metrics\PrometheusMetricFactory:
    arguments:
      $registry: "@keycloak.prometheus.registry"

  KeycloakAuthBundle\Infrastructure\Monitoring\PrometheusCounter:
    arguments:
      $collector: '@KeycloakAuthBundle\Infrastructure\Monitoring\Metrics\PrometheusMetricFactory'

  KeycloakAuthBundle\Domain\Port\MetricsRegistryInterface:
    alias: KeycloakAuthBundle\Infrastructure\Monitoring\PrometheusCounter
